# Generated by Django 4.2.2 on 2023-07-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='short_description',
        ),
    ]
