# Generated by Django 4.2.2 on 2023-07-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_articles_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='topic',
        ),
        migrations.AddField(
            model_name='articles',
            name='topics',
            field=models.ManyToManyField(blank=True, to='food.topic'),
        ),
    ]
